included:
  - Sources
  - Tests

excluded:
  - .build

opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

disabled_rules:
  - todo

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400
